/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-05-17 00:09:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"utf-8\">\r\n");
      out.write("   <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n");
      out.write("   <title>XPectable</title>\r\n");
      out.write("   <link crossorigin=\"anonymous\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("      integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" rel=\"stylesheet\">\r\n");
      out.write("   <link href=\"resources/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"menu_box\">\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("          <hr />\r\n");
      out.write("          <a href=\"index.jsp\"><h3><b style=\"color:#FC6736;font-size:35px\">XP</b>ectable</h3></a>\r\n");
      out.write("          <hr />\r\n");
      out.write("      </div>\r\n");
      out.write("      <ul>\r\n");
      out.write("          <li><a class=\"home\" href=\"index.jsp\"><i class=\"fa fa-home fa-fw\"></i>\r\n");
      out.write("              Home</a></li>\r\n");
      out.write("          <li><a href=\"fixture.jsp\"><i class=\"fa fa-calendar fa-fw\"></i>\r\n");
      out.write("              Fixture</a></li>\r\n");
      out.write("          <li><a href=\"standing.jsp\"><i class=\"fa-solid fa-ranking-star fa-fw\"></i>\r\n");
      out.write("              Standing</a></li>\r\n");
      out.write("          <li><a href=\"stat.jsp\"><i class=\"fa-solid fa-chart-column\"></i>\r\n");
      out.write("              Stats</a></li>\r\n");
      out.write("          <li><a href=\"contact.html\"><i class=\"fa fa-envelope fa-fw\"></i>\r\n");
      out.write("              Contact</a></li>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"social_media\">\r\n");
      out.write("              <a href=\"#\"><i class=\"fa-brands fa-linkedin\" style=\"color:#EFECEC\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fa-brands fa-github\" style=\"color:#EFECEC\"></i></a>\r\n");
      out.write("          </div>\r\n");
      out.write("      </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"row\" style=\"background-image: url(resources/images/up.jpg);background-size: cover;\">\r\n");
      out.write("      <div class=\"summary\">\r\n");
      out.write("         <pre>\r\n");
      out.write("         A better way\r\n");
      out.write("         to predict your\r\n");
      out.write("         team's future\r\n");
      out.write("     </pre>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"two_row\">\r\n");
      out.write("      <div class=\"display_two_column1\">\r\n");
      out.write("         <h2>Features</h2>\r\n");
      out.write("         <p>Maecenas sit amet pretium urna. Vivamus venenatis velit nec neque ultricies,\r\n");
      out.write("            eget elementum magna tristique. Quisque vehicula, risus eget aliquam placerat,\r\n");
      out.write("            purus leo tincidunt eros, eget luctus quam orci in velit. Praesent scelerisque.\r\n");
      out.write("         </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"display_two_column2\">\r\n");
      out.write("         <h2>Feature</h2>\r\n");
      out.write("         <p>Maecenas sit amet pretium urna. Vivamus venenatis velit nec neque ultricies,\r\n");
      out.write("            eget elementum magna tristique. Quisque vehicula, risus eget aliquam placerat,\r\n");
      out.write("            purus leo tincidunt eros, eget luctus quam orci in velit. Praesent scelerisque. \r\n");
      out.write("         </p>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("      <div class=\"display_one_column\">\r\n");
      out.write("         <h2>Specs</h2>\r\n");
      out.write("         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at eleifend massa. Donec aliquet felis sapien,\r\n");
      out.write("            a aliquet enim vulputate in. Donec nulla enim, posuere id aliquam non, mattis sed diam. Phasellus eget\r\n");
      out.write("            neque malesuada, rhoncus ex et, cursus quam. Praesent a sem dui.Suspendisse eu elementum nisi, ut\r\n");
      out.write("            scelerisque magna.\r\n");
      out.write("         </p>\r\n");
      out.write("         <p>Suspendisse eu elementum nisi, ut scelerisque magna. Maecenas eu urna in neque tincidunt luctus.\r\n");
      out.write("            Aliquam justo elit, fermentum sit amet lectus vel, vehicula dictum libero. Vivamus in faucibus eros.\r\n");
      out.write("            Cras volutpat lacinia nisl, in consequat massa pellentesque a. Integer tristique feugiat risus,\r\n");
      out.write("            sed dictum velit iaculis quis. Maecenas interdum tempus porttitor. Vivamus sed magna non nibh condimentum\r\n");
      out.write("            gravida.\r\n");
      out.write("         </p>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- add a footer -->\r\n");
      out.write("   <footer>\r\n");
      out.write("      <p> Allan Emmanuel<br>\r\n");
      out.write("         <a style=\"text-decoration:none\" href=\"mailto:allanfrelens@gamil.com\">allanfrelens@gamil.com</a>\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"social_media\">\r\n");
      out.write("         <a href=\"#\"><i class=\"fa-brands fa-linkedin\" style=\"color:#0C2D57\"></i></a>\r\n");
      out.write("         <a href=\"#\"><i class=\"fa-brands fa-github\" style=\"color:#0C2D57\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
